config/routes.rb
Chalearn::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/signin"

  get "static_pages/signup"

  get "static_pages/challenges"

  get "static_pages/about"

  get "static_pages/contact"

  get "static_pages/wizard"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  

  def home
  end

  def signin
  end

  def signup
  end

  def challenges
  end

  def about
  end

  def wizard
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
   
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", static_pages_home_path %></li>
              <li><%= link_to "Challenges", static_pages_challenges_path %></li>
              <li><%= link_to "Wizard", static_pages_wizard_path %></li>
              <li><%= link_to "Sign in", static_pages_signin_path %></li>
              <li><%= link_to "Sign up", static_pages_signup_path %></li>
              <li><%= link_to "About", static_pages_about_path %></li>
              <li><%= link_to "Contact", static_pages_contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../assets/stylesheets/jumbotron.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="home">ChaLearn</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="home">Home</a></li>
            <li><a href="challenges">Challenges</a></li>
            <li class="active"><a href="about">About us</a></li>
            <li><a href="contact">Contact us</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
            <a href="signup"><button type="button" class="btn btn-info">Sign up</button></a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>About us:</h1>
        <p>


        </p>
      </div>
    </div>

     
      <footer>
        <p>&copy; ChaLearn 2013</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://getbootstrap.com/assets/js/jquery.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
  </body>
</html>

app/views/static_pages/challenges.html.erb
<div class="container">
  <div class="center hero-unit">
    <h1>All your challenges go here</h1>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="center hero-unit">
    <h1>Contact</h1>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="center hero-unit">
    <h1>Home</h1>
    <iframe width="420" height="315" style="margin-top:30px; margin-bottom:30px;" src="http://www.youtube.com/embed/t8g-iYGHpEA" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

app/views/static_pages/signin.html.erb
<div class="container">
  <div class="center hero-unit">
    <h1>Sign in</h1>
  </div>
</div>

app/views/static_pages/signup.html.erb
<div class="container">
  <div class="center hero-unit">
    <form class="form-signin">
      <h2 class="form-signin-heading">Please fill in this form</h2>
      <input type="text" class="form-control" placeholder="Email address" >
  		<br>
      <input type="password" class="form-control" placeholder="Password">
      <br>
        <button class="btn btn-lg btn-primary" type="submit">Create Account</button>
        <a href="home"><button class="btn btn-lg btn-primary">Cancel</button></a>    
    </form>
  </div>
</div>

app/views/static_pages/wizard.html.erb
<% provide(:title, 'Wizard') %>

<div class="container">
  <div class="center hero-unit">
    <h3>Create a new challenge</h3>
        <div class="container">
          <div class="control-group">
            <label for="challenge_title", class="control-label">
              Challenge Title: 
            </label>
            <div class="controls">
              <input name="challenge_title" type="text" value="" id="challenge_title">
            </div>
          </div>
        </div>
        
        <div class="container">
          <input name="start_date" type="text" class='datepicker' id="start_date" placeholder="Start date">
          <script type="text/javascript">
            $(function() { $(".datepicker").datepicker(); });
          </script>
        </div>

        <div class="container">
          <input name="end_date" type="text" class='datepicker' id="end_date" placeholder="End date">
          <script type="text/javascript">
            $(function() { $(".datepicker").datepicker(); });
          </script>
        </div>
  </div>
</div>
  